Plm spare
OmniaGit/odooplm pull request #15
Opened 2018-09-17 14:11 UTC by SalahAdDin

Updated to `pep8` and **Odoo** `11`.

2018-09-19 07:44 UTC, OmniaGit requested changes
please leave the function name as it was.. it will possible brake the client application due to xml-rpc calls

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/models/plm_document_extension.py
> +    used_for_spare = fields.Boolean(_('Used for Spare'),
replace with the old name please...

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/models/plm_temporary.py
> +    def action_create_spare_bom(self):
replace with the old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/models/product_product_extension.py
> +    def action_create_spare_bom_wf(self):
replace with the old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +def get_document_stream(doc_repository, obj_doc):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +def bom_sort(my_object):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +class ReportSparePartsHeader(models.AbstractModel):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +    def get_spare_parts_pdf_file(self, product, output, component_template, bom_template, recursion):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +    def get_pdf_component_layout(self, component):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +    def get_first_page(self, ids):
replace with old name

2018-09-19 07:44 UTC, OmniaGit commented on plm_spare/report/spare_parts_manual.py
> +    def get_report_values(self, doc_ids):
replace with old name

2018-09-19 07:53 UTC, SalahAdDin commented
@OmniaGit But, the old name is not in snake case which is a `pep8` error.

2018-09-30 17:35 UTC, OmniaGit approved these changes

2018-09-30 17:35 UTC, merged